apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-02-12T22:45:35Z"
  generation: 2
  labels:
    run: web-app
  name: web-app
  namespace: default
  resourceVersion: "4880806"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/web-app
  uid: 620cbbc6-4de9-11ea-8239-42010a800207
spec:
  progressDeadlineSeconds: 600
  replicas: 5
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: web-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: web-app
    spec:
      containers:
      - image: ikambarov/web-app:1.0.0
        imagePullPolicy: IfNotPresent
        name: web-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
  - lastTransitionTime: "2020-02-12T22:45:35Z"
    lastUpdateTime: "2020-02-12T22:45:50Z"
    message: ReplicaSet "web-app-64bdb949" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-02-12T22:47:37Z"
    lastUpdateTime: "2020-02-12T22:47:37Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
