apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: webapp
  name: webapp
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: webapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: webapp
    spec:
      containers:
      - image: nginx:1.12
        imagePullPolicy: Always
        name: webapp
        
