apiVersion: v1
kind: Service
metadata:
  labels:
    svc: wordpress-deployment
  name: wordpress-deployment
spec:
  selector:
    app: wordpress-deployment
  ports:
  - name: http
    nodePort: 31372
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  externalTrafficPolicy: Local
